// ... código existente ...

// Traducir mensajes como "Loading..." o "No results found"
<>// ... código existente ...
    // Traducir mensajes como "Loading..." o "No results found"
    <div>Cargando...</div><div>No se encontraron resultados</div></>

// ... resto del código ...